[[override]]
  name = "github.com/xeipuuv/gojsonpointer"
  revision = "4e3ac2762d5f479393488629ee9370b50873b3a6"

[[override]]
  name = "github.com/json-iterator/go"
  revision = "v1.1.5"

[[override]]
  name = "golang.org/x/sys"
  revision = "1b2967e3c290b7c545b3db0deeda16e9be4f98a2"

[[constraint]]
  name = "golang.org/x/net"
  revision = "b3756b4b77d7b13260a0a2ec658753cf48922eac"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "v1.12.0"

[[constraint]]
  name = "github.com/docker/docker"
  revision = "86f080cff0914e9694068ed78d503701667c4c00"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/cri-o/ocicni"
  revision = "fc9c77cc55795c09bf1f74b2afd92078a793a69e"

[[constraint]]
  name = "github.com/docker/distribution"
  revision = "b38e5838b7b2f2ad48e06ec4b500011976080621"

[[override]]
  name = "k8s.io/api"
  revision = "kubernetes-1.13.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "kubernetes-1.13.0"

[[constraint]]
  name = "k8s.io/apiserver"
  revision = "kubernetes-1.13.0"

[[constraint]]
  name = "k8s.io/client-go"
  revision = "kubernetes-1.13.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.13.0"

[[override]]
  name = "k8s.io/utils"
  revision = "0d26856f57b32ec3398579285e5c8a2bfe8c5243"

[[override]]
  name = "k8s.io/klog"
  revision = "8139d8cb77af419532b33dfa7dd09fbc5f1d344f"

[[override]]
  name = "github.com/containerd/cgroups"
  revision = "5e610833b72089b37d0e615de9a92dfc043757c2"

[[override]]
  name = "github.com/containerd/containerd"
  revision = "6937c5a3ba8280edff9e9030767e3b0cb742581c"

[[override]]
  name = "github.com/containerd/fifo"
  revision = "3d5202aec260678c48179c56f40e6f38a095738c"
[[override]]
  name = "github.com/opencontainers/runtime-spec"
  revision = "eba862dc2470385a233c7507392675cbeadf7353"
