apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs-v1
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.99.101
    path: "/var/nfsshare/nfs-v1"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-v1
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
